name: InventoryUIManager
version: '${project.version}'
main: fan.frozen.inventoryuimanager.InventoryUIManager
api-version: 1.18
commands:
  uimanager:
    description: mange UI easily
    permission: op